# Generated by Django 4.1 on 2022-08-30 22:56

import EventoPoesia.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poesia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Carnet', models.CharField(max_length=6)),
                ('Nombre_Completo', models.CharField(max_length=50)),
                ('Direccion', models.CharField(max_length=30)),
                ('Genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('Telefono', models.CharField(max_length=15)),
                ('Fecha_Nacimiento', models.DateField()),
                ('Carrera_Estudiante', models.CharField(max_length=50)),
                ('Genero_Poesia', models.CharField(choices=[('L', 'Lírica'), ('E', 'Épica'), ('D', 'Dramática')], max_length=1)),
                ('Fecha_Inscripcion', models.DateField(verbose_name=EventoPoesia.models.hoy)),
                ('Fecha_Declamacion', models.DateField()),
            ],
        ),
    ]
